name: JojosSMPEngine
main: it.einjojo.smpengine.SMPEnginePlugin
version: ${version}
author: EinJoJo
description: A plugin for SMP Engine
api-version: 1.20
website: einjojo.it
commands:
  smpengine:
    description: SMP ENGINE Admin Command
    aliases: [ smpe, smp , admin]
  team:
    description: Team Commands