version: "3.9"
name: "survival_engine"
services:
  mysql:
    image: mariadb:10.8.3
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: minecraft
    ports:
      - "3306:3306"
  adminer:
    image: adminer
    ports:
      - "8081:8080"